name: mytodo
description: "Welcome to MyTodo's, the perfect solution for managing your tasks effortlessly! Whether you're a busy professional, a student, or just someone with a hectic schedule, our app is designed to simplify your life and boost productivity."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  cached_network_image: ^3.3.1
  flutter_list_view: ^1.1.22
  rive: ^0.13.0
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.3
  hexcolor: ^3.0.1
  intl: ^0.18.1
  responsive_framework: ^1.1.1
  responsive_grid: ^2.4.4
  url_launcher: ^6.2.4
  flutter_redux: ^0.10.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  redux: ^5.0.0
  go_router: ^13.2.0
  flutter_native_splash: ^2.3.10
  flutter_quill: ^9.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_auth: ^4.17.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  flutter_local_notifications: ^17.0.0
  windows_notification: ^1.0.0
  firebase_crashlytics: ^3.4.16
  icons_launcher: ^2.1.7
  easy_localization: ^3.0.5
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.2.0
  firedart: ^0.9.8

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/illustrator/
    - assets/images/bg/
    - assets/translations/


# flutter_native_splash-development.yaml
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  color: "#ffffff"
  image: assets/icon.png
  branding: assets/icon.png
  color_dark: "#121212"
  image_dark: assets/icon.png
  branding_dark: assets/icon.png


  android_12:
    image: assets/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon.png
    icon_background_color_dark: "#121212"

  web: false

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

# webdev serve --auto restart