// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhX4QlsSK_JJO9ZR-Hc3QgSfw1MwPBCXY',
    appId: '1:137948697829:web:40645bcb5c7e4b28e8f00c',
    messagingSenderId: '137948697829',
    projectId: 'my-todo-project-4aee5',
    authDomain: 'my-todo-project-4aee5.firebaseapp.com',
    storageBucket: 'my-todo-project-4aee5.appspot.com',
    measurementId: 'G-P24QYQ775Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJUlXJhWj1jC8ta79vmeikI3geoQBU7s',
    appId: '1:137948697829:android:8b58cfce87de652be8f00c',
    messagingSenderId: '137948697829',
    projectId: 'my-todo-project-4aee5',
    storageBucket: 'my-todo-project-4aee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYEkKIBwZ9PpRU2tzYfyT3nF66nnRmr9g',
    appId: '1:137948697829:ios:92c39514a8cbedbbe8f00c',
    messagingSenderId: '137948697829',
    projectId: 'my-todo-project-4aee5',
    storageBucket: 'my-todo-project-4aee5.appspot.com',
    iosBundleId: 'com.team.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYEkKIBwZ9PpRU2tzYfyT3nF66nnRmr9g',
    appId: '1:137948697829:ios:a13cb9bed4fa7b2ae8f00c',
    messagingSenderId: '137948697829',
    projectId: 'my-todo-project-4aee5',
    storageBucket: 'my-todo-project-4aee5.appspot.com',
    iosBundleId: 'com.team.mytodo.RunnerTests',
  );
}
