// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpG-fKqM2DQp-9y2QVVGgZJ1LtViCIOA',
    appId: '1:110491325321:web:ae0cc32a2eb77c0edd0758',
    messagingSenderId: '110491325321',
    projectId: 'mytodo-s-ed185',
    authDomain: 'mytodo-s-ed185.firebaseapp.com',
    storageBucket: 'mytodo-s-ed185.appspot.com',
    measurementId: 'G-38K6FJT3FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoz6ZWaRKU7Dp7Viobf9BqU5q-UNQM-Yw',
    appId: '1:110491325321:android:e28926d9fa3c6b9bdd0758',
    messagingSenderId: '110491325321',
    projectId: 'mytodo-s-ed185',
    storageBucket: 'mytodo-s-ed185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk_zS74WRaQ231UiJzJlQODJfeMFOBAAQ',
    appId: '1:110491325321:ios:5a10fe5a5a0d0760dd0758',
    messagingSenderId: '110491325321',
    projectId: 'mytodo-s-ed185',
    storageBucket: 'mytodo-s-ed185.appspot.com',
    iosBundleId: 'com.aivilah.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk_zS74WRaQ231UiJzJlQODJfeMFOBAAQ',
    appId: '1:110491325321:ios:668a31472fa6f637dd0758',
    messagingSenderId: '110491325321',
    projectId: 'mytodo-s-ed185',
    storageBucket: 'mytodo-s-ed185.appspot.com',
    iosBundleId: 'com.aivilah.mytodo.RunnerTests',
  );
}
