import 'package:mytodo/control/theme/deserializer.dart';
import 'package:hexcolor/hexcolor.dart';

ThemeDeserializer nightfallThemeObject = ThemeDeserializer(
    primary: HexColor("#5F33E1"),
    onPrimary: HexColor("#2b16a0"),
    secondary: HexColor("#F7A0CD"),
    onSecondary: HexColor("#c67a9b"),
    tertiary: HexColor("#FF7D53"),
    onTertiary: HexColor("#cc4d21"),
    outline: HexColor("#FFFFFF"),
    outlineVariant: HexColor("#D9D9D9"),
    surface: HexColor("#2a2a2a"),
    background: HexColor("#121212"),
    accent: HexColor("#1E1E1E"),
    shadow: HexColor("#ffffff"),
    disabled: HexColor("#4D4D4D"),
    information: HexColor("#007bff"),
    error: HexColor("#F00000"),
    success: HexColor("#379909"),
    radius: 8,
    elevation: 2,
    sm: 4,
    md: 16,
    lg: 24,
    xl: 32,
    smMd: 64,
    smLg: 72,
    smXl: 128,
    brightness: false,
    material: true,
    fontFamily: "Roboto",
    fontFamilyFallback: ["Arial", "Helvetica"],
    display: "IBM Plex Sans",
    headline: "Montserrat",
    title: "Source Code Pro",
    body: "Lato",
    label: "Nunito");
